name: GitHub Score update
run-name: ${{ github.actor }} is testing updating scores ğŸš€
on: [push]
jobs:
  Compute-Score-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cd ${{ github.workspace }}
          ls
      - name: Compute new scores
        run: |
          cd ${{ github.workspace }}
          ls ./
          ls ${{ github.workspace }}
          ./compute_score.sh
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - run: |
          git config --global user.name 'nsutter'
          git config --global user.email 'suttercyril.sutternicolas@gmail.com'
          git commit -am "Update scores"
          git push
